# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cc841b025938330c77518b90a6a090ca6ff9f5170e534d615f6fb59e8d5ac35689dde64d5d8e218dfc25fc0499a0687c0f518498650b122a2f4e9ec854d1c67

test:
  secret_key_base: 9571cedd93e1db86e404ff0bd4401c1916d3aab3a0b41a792dea04086ad1d3058cf36d42353a6db1e249b3c8ea908beba6f22bed410e29561b6b31683e139b96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
